from __future__ import annotations as _annotations

from ._version import __version__
from .agent_source import AgentFactory, AgentSource, FactoryAgentSource, StaticAgentSource
from .agent_types import RuntimeAgent
from .approval_store import (
    ApprovalPolicy,
    ApprovalPolicyStore,
    PermissionOptionSet,
    SessionMetadataApprovalPolicyStore,
)
from .approvals import (
    ApprovalBridge,
    NativeApprovalBridge,
    ProjectionAwareApprovalBridge,
    supports_projection_aware_approval_bridge,
)
from .bridges import (
    AnthropicCompactionBridge,
    BufferedCapabilityBridge,
    CapabilityBridge,
    EventEmissionMode,
    ExternalHookEventBridge,
    HistoryProcessorBridge,
    HistoryProcessorCallable,
    HistoryProcessorContextual,
    HistoryProcessorPlain,
    HistoryProcessorWithContextAsync,
    HistoryProcessorWithContextSync,
    HookBridge,
    ImageGenerationBridge,
    IncludeToolReturnSchemasBridge,
    McpBridge,
    McpCapabilityBridge,
    McpServerDefinition,
    McpToolDefinition,
    OpenAICompactionBridge,
    PlanGenerationType,
    PrefixToolsBridge,
    PrepareOutputToolsBridge,
    PrepareOutputToolsMode,
    PrepareToolsBridge,
    PrepareToolsMode,
    SetToolMetadataBridge,
    ThinkingBridge,
    ThreadExecutorBridge,
    ToolsetBridge,
    WebFetchBridge,
    WebSearchBridge,
)
from .builders import AgentBridgeBuilder, AgentBridgeContributions
from .config import AdapterConfig
from .hook_projection import HookEvent, HookProjectionMap
from .host import (
    ClientFilesystemBackend,
    ClientHostContext,
    ClientTerminalBackend,
    FilesystemBackend,
    HostAccessDisposition,
    HostAccessPolicy,
    HostCommandEvaluation,
    HostPathEvaluation,
    HostRisk,
    TerminalBackend,
)
from .models import AdapterModel
from .permission_presentation import (
    DefaultPermissionToolCallBuilder,
    PermissionRequestContext,
    PermissionToolCallBuilder,
)
from .projection import (
    BuiltinToolProjectionMap,
    CompositeProjectionMap,
    FileSystemProjectionMap,
    ProjectionAwareToolClassifier,
    ProjectionMap,
    WebToolProjectionMap,
    compose_projection_maps,
)
from .projection_helpers import (
    DEFAULT_TEXT_TRUNCATION_MARKER,
    caution_for_command,
    caution_for_path,
    format_code_block,
    format_diff_preview,
    format_terminal_status,
    single_line_summary,
    truncate_lines,
    truncate_text,
)
from .prompt_capabilities import AdapterPromptCapabilities
from .providers import (
    ApprovalStateProvider,
    ConfigOption,
    ConfigOptionsProvider,
    ModelSelectionState,
    ModeState,
    NativePlanPersistenceProvider,
    PlanProvider,
    PromptModelOverrideProvider,
    SessionModelsProvider,
    SessionModesProvider,
)
from .runtime.hook_introspection import RegisteredHookInfo, list_agent_hooks
from .runtime.server import create_acp_agent, run_acp
from .session.state import AcpSessionContext, JsonValue
from .session.store import FileSessionStore, MemorySessionStore, SessionStore
from .slash import (
    SlashCommandHandler,
    SlashCommandProvider,
    SlashCommandRequest,
    SlashCommandResult,
    StaticSlashCommand,
    StaticSlashCommandProvider,
)
from .testing import BlackBoxHarness, RecordingACPClient, UpdateRecord, agent_message_texts
from .types import (
    AcpAgent,
    AgentPromptBlock,
    AudioContentBlock,
    BlobResourceContents,
    EmbeddedResourceContentBlock,
    HttpMcpServer,
    ImageContentBlock,
    McpServerStdio,
    PlanEntry,
    ResourceContentBlock,
    SseMcpServer,
    TextContentBlock,
    TextResourceContents,
)

__all__ = (
    "AcpSessionContext",
    "AcpAgent",
    "AgentFactory",
    "AgentPromptBlock",
    "AgentSource",
    "ApprovalBridge",
    "ApprovalStateProvider",
    "AdapterConfig",
    "AdapterModel",
    "AgentBridgeBuilder",
    "AgentBridgeContributions",
    "AnthropicCompactionBridge",
    "AudioContentBlock",
    "BufferedCapabilityBridge",
    "BlackBoxHarness",
    "BlobResourceContents",
    "BuiltinToolProjectionMap",
    "CapabilityBridge",
    "ClientFilesystemBackend",
    "ClientHostContext",
    "ClientTerminalBackend",
    "ConfigOption",
    "ConfigOptionsProvider",
    "CompositeProjectionMap",
    "compose_projection_maps",
    "caution_for_command",
    "caution_for_path",
    "DEFAULT_TEXT_TRUNCATION_MARKER",
    "DefaultPermissionToolCallBuilder",
    "EmbeddedResourceContentBlock",
    "EventEmissionMode",
    "ExternalHookEventBridge",
    "FileSessionStore",
    "FileSystemProjectionMap",
    "FactoryAgentSource",
    "FilesystemBackend",
    "HostAccessDisposition",
    "HostAccessPolicy",
    "HostCommandEvaluation",
    "HostPathEvaluation",
    "HostRisk",
    "HistoryProcessorCallable",
    "HistoryProcessorBridge",
    "HistoryProcessorContextual",
    "HistoryProcessorPlain",
    "HistoryProcessorWithContextAsync",
    "HistoryProcessorWithContextSync",
    "HookEvent",
    "HookProjectionMap",
    "HookBridge",
    "HttpMcpServer",
    "ImageGenerationBridge",
    "ImageContentBlock",
    "IncludeToolReturnSchemasBridge",
    "JsonValue",
    "list_agent_hooks",
    "MemorySessionStore",
    "McpCapabilityBridge",
    "McpBridge",
    "McpServerDefinition",
    "McpServerStdio",
    "McpToolDefinition",
    "ModeState",
    "ModelSelectionState",
    "NativeApprovalBridge",
    "NativePlanPersistenceProvider",
    "OpenAICompactionBridge",
    "AdapterPromptCapabilities",
    "PlanEntry",
    "PlanGenerationType",
    "PlanProvider",
    "PrefixToolsBridge",
    "ApprovalPolicy",
    "ApprovalPolicyStore",
    "ProjectionMap",
    "ProjectionAwareApprovalBridge",
    "ProjectionAwareToolClassifier",
    "PromptModelOverrideProvider",
    "PermissionOptionSet",
    "PermissionRequestContext",
    "PermissionToolCallBuilder",
    "ResourceContentBlock",
    "format_code_block",
    "format_diff_preview",
    "format_terminal_status",
    "PrepareOutputToolsBridge",
    "PrepareOutputToolsMode",
    "PrepareToolsBridge",
    "PrepareToolsMode",
    "RegisteredHookInfo",
    "RecordingACPClient",
    "RuntimeAgent",
    "SetToolMetadataBridge",
    "ThinkingBridge",
    "ThreadExecutorBridge",
    "ToolsetBridge",
    "WebFetchBridge",
    "WebSearchBridge",
    "WebToolProjectionMap",
    "SessionStore",
    "SessionMetadataApprovalPolicyStore",
    "SessionModelsProvider",
    "SessionModesProvider",
    "SlashCommandHandler",
    "SlashCommandProvider",
    "SlashCommandRequest",
    "SlashCommandResult",
    "StaticAgentSource",
    "StaticSlashCommand",
    "StaticSlashCommandProvider",
    "SseMcpServer",
    "single_line_summary",
    "TerminalBackend",
    "TextContentBlock",
    "TextResourceContents",
    "truncate_lines",
    "truncate_text",
    "UpdateRecord",
    "__version__",
    "agent_message_texts",
    "create_acp_agent",
    "run_acp",
    "supports_projection_aware_approval_bridge",
)
